# Generated by Django 3.0.5 on 2020-07-16 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10 digit number', regex='^[6789]{1}\\d{9}')])),
                ('otp', models.CharField(max_length=10)),
                ('verified', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='encrypted_private_key',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='licence_no',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='public_key',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='encrypted_private_key',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='public_key',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_private_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='licence_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('Male', 'MALE'), ('Female', 'FEMALE'), ('Other', 'OTHER')], default=None, max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('Doctor', 'DOCTOR'), ('Patient', 'PATIENT'), ('Admin', 'Admin')], default=None, max_length=7),
        ),
    ]
