# Generated by Django 3.0.5 on 2020-07-22 13:05

from django.db import migrations
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_patientrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='record',
            field=django_encrypted_filefield.fields.EncryptedFileField(upload_to=''),
        ),
    ]
