# Generated by Django 3.0.5 on 2020-07-24 10:08

import Users.models
from django.db import migrations, models
import django.utils.timezone
import django_encrypted_filefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0005_auto_20200722_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientrecord',
            name='record',
            field=django_encrypted_filefield.fields.EncryptedFileField(upload_to=Users.models.PatientRecord.user_directory_path),
        ),
    ]
