# Generated by Django 3.0.5 on 2020-07-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0006_auto_20200724_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='doctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Doctor'),
        ),
        migrations.AddField(
            model_name='phoneotp',
            name='patient_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Users.Patient'),
        ),
    ]
