# Generated by Django 3.1 on 2020-08-07 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_auto_20200807_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Weight',
            new_name='weight',
        ),
    ]
